version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: proposidocs.fernandocunha.click
        BUILD_FOLDER: dist
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
            - npm install --save-dev @angular-devkit/build-angular
    build:
        commands:
            - echo Build started on `date`
            - pwd
            - ls -l
            - cd proposiDocs
            - npm install
            - ng build
            - ls -l
    post_build:
         commands:
            - pwd; ls -l
            - cd ${BUILD_FOLDER}/proposiDocs
            - aws s3 cp . s3://${S3_BUCKET} --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}"
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist'
    discard-paths: yes